/**
 * Finn Tone API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import Tone from '../model/Tone';

/**
* Tone service.
* @module api/ToneApi
* @version 1.0.0
*/
export default class ToneApi {

    /**
    * Constructs a new ToneApi. 
    * @alias module:api/ToneApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the loadToneById operation.
     * @callback module:api/ToneApi~loadToneByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Tone} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get tone of a user
     * @param {String} userId The id of the user whose tone to retrieve
     * @param {module:api/ToneApi~loadToneByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Tone}
     */
    loadToneById(userId, callback) {
      let postBody = null;
      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling loadToneById");
      }

      let pathParams = {
        'userId': userId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Tone;
      return this.apiClient.callApi(
        '/tone/{userId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
